locale: fr

backend:
  name: git-gateway
  branch: netlifyCMS # Branch to update (optional; defaults to master)
  squash_merges: true

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    format: json
    folder: "src/text" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Couleur fond"
        name: "color"
        widget: "select"
        default: "white"
        options: 
          - {label: "bleu foncé", value: "theme-dark-blue"}
          - {label: "noir", value: "theme-black"} 
          - {label: "orange", value: "theme-orange"}
          - {label: "blanc", value: "theme-white"}
      - label: "Icone"
        name: "icon"
        widget: "select"
        required: false
        default: "exclamation-circle"
        options:
          - {label: "poisson", value: "fish"}
          - {label: "important", value: "exclamation-circle"} 
          - {label: "nuage", value: "cloud"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "startDate", widget: "datetime", default: '', required: false}
      - {label: "Date de fin", name: "endDate", widget: "datetime", default: '', required: false}
      - {label: "Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Corps", name: "body", widget: "markdown", required: false}
  - name: "agenda" # Used in routes, e.g., /admin/collections/blog
    label: "Agenda" # Used in the UI
    format: json
    folder: "src/agenda" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Date", name: "startDate", widget: "datetime", default: '', required: false}
      - {label: "Date de fin", name: "endDate", widget: "datetime", default: '', required: false}
      - {label: "Corps", name: "body", widget: "markdown", required: false}
      - {label: "Image", name: "thumbnail", widget: "image", required: false}